# serverless.yml

service: billing-db

# app: billing-db
# org: julesballaran

plugins:
  - serverless-offline
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'
  serverless-offline:
    port: 15001

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
# package:
#   exclude:
#     - node_modules/**
